export enum EnumStatusArticle {
	ARTICLE_NON_ENVOYE = 1,
	ARTICLE_ENVOYE_SUR_LA_ROUTE = 2,
	ARTICLE_ARRIVE_EN_CHINE_MANQUE_INFO_CLIENT = 3,
	ARTICLE_ARRIVE_EN_CHINE_PRET_A_DISTRIBUER = 4,
	ARTICLE_ENVOYE_AU_CLIENT = 5,
	ARTICLE_TERMINE = 6
}